services:
  backend:
    build: .
    container_name: travel-resolver-api
    ports:
      - '8000:8000'
    command:
      [
        'uv',
        'run',
        'uvicorn',
        'backend.app.main:app',
        '--host',
        '0.0.0.0',
        '--port',
        '8000',
      ]
    volumes:
      - .:/app
    restart: unless-stopped

  frontend:
    build: .
    container_name: travel-resolver-front
    ports:
      - '8501:8501'
    command:
      [
        'uv',
        'run',
        'streamlit',
        'run',
        'frontend/app.py',
        '--server.address',
        '0.0.0.0',
        '--server.port',
        '8501',
      ]
    volumes:
      - .:/app
    depends_on:
      - backend
    restart: unless-stopped
